### PR TITLE
Add a simple Typescript definition

### LINKED ISSUE #29: Typescript definition file
Would you be interested in adding a Typescript definition file to your npm package? I'd be happy to contribute one via PR and help maintain it. There are other places to host such files, but it's always nicest when they exist right along the npm install.

(I ask first as an issue instead of sending a PR first as a courtesy, because I know not everyone wants to maintain Typescript definitions and "no" is a perfectly fine answer.)

### PR DESCRIPTION
**Pull request by WorldMaker**
This should usefully define the library enough for Typescript.

Resolves #29 

Thanks.

### CODE REVIEW

**Comment by alizain** [comment]
@WorldMaker, naming convention for the library is preferably `ulid`, or `ULID`. I'll make the changes in the README, please make the changes in this PR (unless TypeScript has a specific naming convention for interfaces)

**Comment by WorldMaker** [comment]
That interface isn't exported from the file, it's an internal detail. The actual export name is `ulid` except that's also primarily an internal detail because of the way it is mimicking the way that the `index.js` exports itself as a node module (`module.exports = ulid` rather than `module.exports.ulid = ulid` or similar).

**Comment by WorldMaker** [comment]
For further clarification, the big reason it needed an interface as an internal detail at all is because Typescript follows ES2015 modules a bit closer than CommonJS modules and you can't directly export a "nameless" function. What I'd somewhat prefer to do:

```
export function prng(): number
export function encodeTime(...): string
// ...
export function ulid(...): string
```

But that last function isn't actually named that way in the Node CommonJS export here. It doesn't have a name at all from the perspective of an ES2015 module. (...and technically is illegal in the ES2015 module spec.)

**Comment by WorldMaker** [comment]
(In my tooling this sort of export gets referred to as a "synthetic default" because the closest equivalent is a ES2015 `default` export, but default has the name `default`.)

**Comment by WorldMaker** [comment]
Hope all the above helps more than it confuses. 😸

**Comment by alizain** [comment]
Intereesstingggg... thanks for the explanation.

As I understand it, the following are equal in practice:
```javascript
// ES5 (CommonJS)
var obj = {
    one: 1
    two: 2
}
module.exports = obj

// ES6
export const one = 1
export const two = 2
const obj = {
    obj,
    two
}
export default obj
```

So, the way this module exports is akin to saying `export default ulid`, which both CommonJS and ES6 will understand. However, upon further research, it would seem that ES6 modules are flat in structure, thereby assigning the name `default` to the default export, instead of the object namespace export of CommonJS.

Therefore, on the question of exporting with maximum compatibility and ease of use for ES6, CommonJS, and browser-based environments, it is my perspective that this is the best way to go. What are your thoughts from your perspective (especially as a TS user, which I am not)?

Finally, for the initial comment itself, I was not at all referring to any specific thing the code you submitted does, but instead I was making a superficial nitpick.

**Comment by WorldMaker** [comment]
Yeah, I wasn't taking a offense to the superficial nitpick, but it is a weirdly complex topic. What I've done is try to model the way the module *acts* today, rather than necessarily what you or I would like it to be.

ES2015 modules build a "module proxy object" rather than an object directly. (Both because ES2015 modules are immutable/static after import and because ES2015 modules support complicated things like circular imports.) Calling one of these "module proxy objects" is actually disallowed in ES2015:

```ts
import * as ulid from 'ulid' // closest ES2015 equivalent to: var ulid = require('ulid')

ulid() // This is a runtime error in ES2015: modules are not callable
```

The bare import (`import ulid from 'ulid'`) is the default import and yes, superficially it looks like the default export is what we want and equivalent, but it's not how this module is currently implemented. Because if you export a default export, in NodeJS you do need to address it as `var ulid = require('ulid').default`.

In Typescript if I were to type it as a default export then its type information expects CommonJS users need to do that `require('...').default`, which is not how you would use the library today, so I have to model it as an `export = obj` because that's the equivalent in Typescript to how it is currently defined.

(Aside, my ES2015-influenced loader enforces the module objects are not allowed to be callable and I'd get a runtime error trying to call it, but it is also kind enough to model this sort of CommonJS library as if it were a default export, and I have to use the flag `--allowSyntheticDefaults` in Typescript to treat this sort of export as if it were a default export.)

**Comment by WorldMaker** [comment]
One of these days, hopefully, there will be fewer module systems to need to know. But that day is not yet today. 😞

**Comment by alizain** [comment]
> ES2015 modules build a "module proxy object" rather than an object directly.

Precisely as I have now learned.

> Because if you export a default export, in NodeJS you do need to address it as var ulid = require('ulid').default.

Which is poor UI, imho, but the real sticking point to exporting properly as default

Crucially, as exported, the following code works with ES6:
```javascript
import ulid, { encodeRandom } from 'ulid'
```

Therefore, I'm really satisfied with your modelling of the interface as presented today. Thanks for the great PR and awesome conversation 😊

**Comment by WorldMaker** [comment]
Welcome :D

**Pull request merged**
