### PR TITLE
Fix time byte ordering in binary diagram

### PR DESCRIPTION
**Pull request by tsenart**
Ref: https://github.com/RobThree/NUlid/issues/1

### CODE REVIEW

**Comment by tsenart** [comment]
@alizain: BTW, would you please link my `go-ulid` implementation in the README? Have a look at it too :-)

**Comment by imdario** [comment]
It is a honor to have a repo forked by @tsenart :+1: If you want to create a PR for your commits, I'll be happy to merge them and give proper credit.

**Comment by tsenart** [comment]
@imdario: Don't make me blush :-) I'm afraid it started as a fork for some little changes, but it became a full blown re-write. There's not much left of the original code. Do you think I should re-open the from scratch repo?

**Comment by imdario** [comment]
If that is the case, I think you should. I'll check your implementation and decide what I'll do with mine. In any case, I'll link yours.

**Comment by tsenart** [comment]
@imdario: https://github.com/oklog/ulid

**Comment by tsenart** [comment]
@alizain: Ping

**Comment by alizain** [comment]
🎉 thanks @tsenart, sorry for the delay!

**Comment by tsenart** [comment]
@alizain: No worries. You're welcome! Also, wanna link the repo in your README?

**Pull request merged**
